# Generated by Django 6.0.4 on 2026-05-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='service_images'),
        ),
    ]
