# Generated by Django 6.0.4 on 2026-05-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_category_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='category_icons'),
        ),
    ]
