# Generated by Django 6.0.4 on 2026-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_alter_review_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, upload_to='review_pics'),
        ),
    ]
