# Generated by Django 6.0.4 on 2026-05-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_review_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
