# Generated by Django 6.0.4 on 2026-05-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookings_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
