# Generated by Django 6.0.4 on 2026-04-30 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owned_company',
        ),
        migrations.AddField(
            model_name='company',
            name='company_admin',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owned_company', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
