# Generated by Django 6.0.4 on 2026-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='emp_pic'),
        ),
    ]
